project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

execute:
  freeze: true
