project:
  type: manuscript

manuscript:
  manuscript-url: "https://matteospanio.github.io/multimodal-symphony-survey-analysis/"
  code-links:
    - repo
    - binder
    - text: Data Import and Cleaning
      href: src/load_data.R
    - text: Utility Functions
      href: src/utils.R
  article: index.qmd

format:
  html:
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

execute:
  freeze: true
